set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)

set(CMAKE_C_COMPILER /usr/bin/cc)
set(CMAKE_CXX_COMPILER /usr/bin/c++)

set(COMPILER_WORKS_EXITCODE 0)
set(COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT 0)
set(BLAS_F2C_DOUBLE_WORKS_EXITCODE 0)
set(BLAS_F2C_DOUBLE_WORKS_EXITCODE__TRYRUN_OUTPUT 0)
set(BLAS_USE_CBLAS_DOT_EXITCODE 0)
set(BLAS_USE_CBLAS_DOT__EXITCODE__TRYRUN_OUTPUT 0)
set(CMAKE_SYSROOT /)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set( BLAS_F2C_FLOAT_WORKS_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_F2C_FLOAT_WORKS_EXITCODE__TRYRUN_OUTPUT
     "ok"
     CACHE STRING "Output from TRY_RUN" FORCE)

set( BLAS_USE_CBLAS_DOT_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

set( BLAS_USE_CBLAS_DOT_EXITCODE__TRYRUN_OUTPUT
     "ok"
     CACHE STRING "Output from TRY_RUN" FORCE)
